// Generated by CoffeeScript 1.7.1
(function() {
  Template.messages.messages = function() {
    return Messages.find({}, {
      sort: {
        time: -1
      }
    });
  };

  Template.input.events({
    'submit form': function(e, template) {
      var message, name;
      e.preventDefault();
      if (Meteor.user()) {
        name = Meteor.user().emails[0].address;
      } else {
        name = 'Anonymous';
      }
      message = template.find('#message').value;
      if (message !== '') {
        Messages.insert({
          name: name,
          message: message,
          time: Date.now()
        });
        return template.find('#message').value = '';
      }
    }
  });

}).call(this);
